title: "Utopian Studies"
description: "Video lessons and resources from Dr. Mmeskerem Lechisa"

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme


# Because this is a project site (repo is /utopia)
baseurl: "/utopia"
url: "https://lydiavasil.github.io"

collections:
  lessons:
    output: true
    permalink: /lessons/:name/

just_the_docs:
  search_enabled: true
  navigation_sort: case_insensitive
  footer_content: "Â© 2025 Meskerem Lechisa"
